export const images = [
    { src: 'https://picsum.photos/800/400?random', alt: 'Imagens geradas de forma aleatoria', wide: true }, 
    { src: 'https://picsum.photos/800/400?random=2', alt: 'Imagens geradas de forma aleatoria'}, 
    { src: 'https://picsum.photos/800/400?random=3', alt: 'Imagens geradas de forma aleatoria'}, 
    { src: 'https://picsum.photos/800/400?random=4', alt: 'Imagens geradas de forma aleatoria', wide: true }, 
    { src: 'https://picsum.photos/800/400?random=5', alt: 'Imagens geradas de forma aleatoria' }, 
    { src: 'https://picsum.photos/800/400?random=6', alt: 'Imagens geradas de forma aleatoria'}, 
    { src: 'https://picsum.photos/800/400?random=7', alt: 'Imagens geradas de forma aleatoria'}, 
    { src: 'https://picsum.photos/800/400?random=8', alt: 'Imagens geradas de forma aleatoria', wide: true }, 
    { src: 'https://picsum.photos/800/400?random=9', alt: 'Imagens geradas de forma aleatoria'}, 
    { src: 'https://picsum.photos/800/400?random=10', alt: 'Imagens geradas de forma aleatoria'}, 
    { src: 'https://picsum.photos/800/400?random=11', alt: 'Imagens geradas de forma aleatoria', wide: true }, 
    { src: 'https://picsum.photos/800/400?random=12', alt: 'Imagens geradas de forma aleatoria'}, 
    { src: 'https://picsum.photos/800/400?random=13', alt: 'Imagens geradas de forma aleatoria', wide: true }, 
    { src: 'https://picsum.photos/800/400?random=14', alt: 'Imagens geradas de forma aleatoria', wide: true }, 
    { src: 'https://picsum.photos/800/400?random=15', alt: 'Imagens geradas de forma aleatoria'}, 
    { src: 'https://picsum.photos/800/400?random=16', alt: 'Imagens geradas de forma aleatoria'}, 
    { src: 'https://picsum.photos/800/400?random=17', alt: 'Imagens geradas de forma aleatoria', wide: true }, 
    { src: 'https://picsum.photos/800/400?random=18', alt: 'Imagens geradas de forma aleatoria'},
    { src: 'https://picsum.photos/800/400?random=19', alt: 'Imagens geradas de forma aleatoria'}, 
    { src: 'https://picsum.photos/800/400?random=20', alt: 'Imagens geradas de forma aleatoria'}, 
]